
name: GitHub Actions Demo
on: [ push ]
jobs:
  Test:
    runs-on: windows
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: python main.py
